name: DoNotJump
main: me.tsunami.donotjump.Main
author: Tsunami#6271
version: 1.0
commands:
  donotjump:
    description: The help command of DoNotJump.
  dnjhelp:
    description: The help command of DoNotJump.
  dnjconfig:
    description: Change the config of DoNotJump.
  dnjreload:
    description: Reload DoNotJump.
permissions:
  donotjump.*:
    default: op